// code generated by [generate-resource-dart-code] vscode-extension.
class AssetsImages {
  static const bodySebhaDark@2xPng = 'assets/images/2.0x/body_sebha_dark@2x.png';
  static const bodySebhaDark@3xPng = 'assets/images/3.0x/body_sebha_dark@3x.png';
  static const bodySebhaDarkPng = 'assets/images/body_sebha_dark.png';
  static const bodySebhaLogo@2xPng = 'assets/images/2.0x/body_sebha_logo@2x.png';
  static const bodySebhaLogo@3xPng = 'assets/images/3.0x/body_sebha_logo@3x.png';
  static const bodySebhaLogoPng = 'assets/images/body_sebha_logo.png';
  static const darkBg@2xPng = 'assets/images/2.0x/dark_bg@2x.png';
  static const darkBg@3xPng = 'assets/images/3.0x/dark_bg@3x.png';
  static const darkBgPng = 'assets/images/dark_bg.png';
  static const defaultBg@2xPng = 'assets/images/2.0x/default_bg@2x.png';
  static const defaultBg@3xPng = 'assets/images/3.0x/default_bg@3x.png';
  static const defaultBgPng = 'assets/images/default_bg.png';
  static const hadethLogo@2xPng = 'assets/images/2.0x/hadeth_logo@2x.png';
  static const hadethLogo@3xPng = 'assets/images/3.0x/hadeth_logo@3x.png';
  static const hadethLogoPng = 'assets/images/hadeth_logo.png';
  static const headSebhaDark@2xPng = 'assets/images/2.0x/head_sebha_dark@2x.png';
  static const headSebhaDark@3xPng = 'assets/images/3.0x/head_sebha_dark@3x.png';
  static const headSebhaDarkPng = 'assets/images/head_sebha_dark.png';
  static const headSebhaLogo@2xPng = 'assets/images/2.0x/head_sebha_logo@2x.png';
  static const headSebhaLogo@3xPng = 'assets/images/3.0x/head_sebha_logo@3x.png';
  static const headSebhaLogoPng = 'assets/images/head_sebha_logo.png';
  static const iconHadeth@2xPng = 'assets/images/2.0x/icon_hadeth@2x.png';
  static const iconHadeth@3xPng = 'assets/images/3.0x/icon_hadeth@3x.png';
  static const iconHadethPng = 'assets/images/icon_hadeth.png';
  static const iconQuran@2xPng = 'assets/images/2.0x/icon_quran@2x.png';
  static const iconQuran@3xPng = 'assets/images/3.0x/icon_quran@3x.png';
  static const iconQuranPng = 'assets/images/icon_quran.png';
  static const iconRadio@2xPng = 'assets/images/2.0x/icon_radio@2x.png';
  static const iconRadio@3xPng = 'assets/images/3.0x/icon_radio@3x.png';
  static const iconRadioPng = 'assets/images/icon_radio.png';
  static const iconSebha@2xPng = 'assets/images/2.0x/icon_sebha@2x.png';
  static const iconSebha@3xPng = 'assets/images/3.0x/icon_sebha@3x.png';
  static const iconSebhaPng = 'assets/images/icon_sebha.png';
  static const qur2anScreenLogo@2xPng = 'assets/images/2.0x/qur2an_screen_logo@2x.png';
  static const qur2anScreenLogo@3xPng = 'assets/images/3.0x/qur2an_screen_logo@3x.png';
  static const qur2anScreenLogoPng = 'assets/images/qur2an_screen_logo.png';
  static const radioImage@2xPng = 'assets/images/2.0x/radio_image@2x.png';
  static const radioImage@3xPng = 'assets/images/3.0x/radio_image@3x.png';
  static const radioImagePng = 'assets/images/radio_image.png';
}

class AssetsSvgs {

}

